pipeline {

   agent none

   triggers { pollSCM('H/2 * * * *') }

    stages {
        stage('Build') {
            agent {
              docker {
                image 'python:2.7-alpine'
                args '--user root'
              }
            }
            steps {
                echo 'Building..'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            agent {
              docker {
                image 'python:2.7-alpine'
                args '--user root'
              }
            }
            steps { 
                echo 'Testing..'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
                  sh 'nosetests -v'
                }
            }
        }

        stage('Package with Docker') {
            agent any
            steps {
                echo 'Building and Publishing Docker Image'
                script {
                  docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                    def customImage = docker.build("initcron/votetest:${env.BRANCH_NAME}-${env.BUILD_ID}", "./vote")
                    customImage.push("${env.BRANCH_NAME}")
                    customImage.push()
                  }
                }
            }
        }
    }
}
