pipeline {

   agent {
        docker {
            image 'python:2.7-alpine'
            args '--user root'
        }
    }


    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
                }
            }
            }

        stage('Test') {
            steps {
                echo 'Testing..'
                dir('vote'){
                  sh 'nosetests -v'
                }
            }
        }
    }
}
