pipeline {
  agent{
    docker{
      image 'maven:3.6.1-jdk-8-slim'
      args '-v $HOME/.m2:/root/.m2'
    }
  }  
  stages{
      stage("build"){
          steps{
              echo 'Compiling worker app'
              dir('worker'){
                sh 'mvn compile'
              }
          }
      }
      stage("test"){
          steps{
              echo 'Running Unit Tets on worker app'
	      dir('worker'){
		sh 'mvn clean test'
	      }
         
	 }
      }
      stage("package"){
        steps{
          echo 'Packaging worker app'
	  dir('worker'){
		sh 'mvn package -DskipTests'
		archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
	  }

        }
      }
  }

  post{
    always{
	echo 'This job is complete'
    }
	  success {
           slackSend (channel: "instavote", message: "Build Succes - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
       }
    failure {
           slackSend (channel: "instavote", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
       }
  }
}
