pipeline {

    agent any

    tools{
      maven "Maven 3.6.1"
    }

    stages{
        stage('Build'){
            steps{
                echo "Compiling work app"
                dir{'worker'}{
                  sh 'mvn compile'
                }
            }
        }
        stage('Test'){
            steps{
                echo "Running Unit Test on worker app"
                sleep 6
            }
        }
        stage('Package'){
            steps{
                echo "Packaging worker app"
                sleep 9
            }
        }
    }

  post {
      always{
          echo "This pipeline run is complete."
      }

  }
}
